// ============================================================
// SISTEMA DE IMAGENES MANUALES DE BACTERIDEX
// ============================================================
// No se descarga nada de Internet automaticamente. Todo es manual.
//
// Cada microorganismo tiene EXACTAMENTE dos imagenes editables:
//   1) Microscopica (tincion de Gram / microscopia)
//   2) Agar (fotografia del microorganismo en placa/cultivo)
// No agregar mas mapas de imagenes por microorganismo que estos dos.
//
// Para agregar una imagen:
// 1. Sube el archivo a /public/images/<categoria>/tu-imagen.jpg
//    (categorias: bacterias, virus, hongos, parasitos, medios-cultivo)
// 2. Reemplaza el `null` de la linea correspondiente por la ruta, ej:
//    b001: "/images/bacterias/staphylococcus-aureus-microscopica.jpg",
// 3. Guarda. No hace falta tocar ningun otro archivo.
//
// Si el valor sigue en null, la ficha muestra un placeholder ilustrado
// automaticamente (nunca se rompe ni muestra una imagen caida).

export type MapaImagenes = Record<string, string | null>;

// MICROORGANISMOS (BACTERIAS, VIRUS, HONGOS, PARASITOS) — MICROSCOPICA (tincion de Gram / microscopia)
export const imagenesMicroscopica: MapaImagenes = {
  b001: null, // === AQUI VA IMAGEN MICROSCOPICA DE STAPHYLOCOCCUS AUREUS / TINCION DE GRAM ===
  b002: null, // === AQUI VA IMAGEN MICROSCOPICA DE STAPHYLOCOCCUS EPIDERMIDIS / TINCION DE GRAM ===
  b003: null, // === AQUI VA IMAGEN MICROSCOPICA DE STAPHYLOCOCCUS SAPROPHYTICUS / TINCION DE GRAM ===
  b004: null, // === AQUI VA IMAGEN MICROSCOPICA DE STREPTOCOCCUS PYOGENES / TINCION DE GRAM ===
  b005: null, // === AQUI VA IMAGEN MICROSCOPICA DE STREPTOCOCCUS AGALACTIAE / TINCION DE GRAM ===
  b006: null, // === AQUI VA IMAGEN MICROSCOPICA DE STREPTOCOCCUS PNEUMONIAE / TINCION DE GRAM ===
  b007: null, // === AQUI VA IMAGEN MICROSCOPICA DE ENTEROCOCCUS FAECALIS / TINCION DE GRAM ===
  b008: null, // === AQUI VA IMAGEN MICROSCOPICA DE ESCHERICHIA COLI / TINCION DE GRAM ===
  b009: null, // === AQUI VA IMAGEN MICROSCOPICA DE KLEBSIELLA PNEUMONIAE / TINCION DE GRAM ===
  b010: null, // === AQUI VA IMAGEN MICROSCOPICA DE PROTEUS MIRABILIS / TINCION DE GRAM ===
  b011: null, // === AQUI VA IMAGEN MICROSCOPICA DE SALMONELLA ENTERICA / TINCION DE GRAM ===
  b012: null, // === AQUI VA IMAGEN MICROSCOPICA DE SHIGELLA FLEXNERI / TINCION DE GRAM ===
  b013: null, // === AQUI VA IMAGEN MICROSCOPICA DE PSEUDOMONAS AERUGINOSA / TINCION DE GRAM ===
  b014: null, // === AQUI VA IMAGEN MICROSCOPICA DE ACINETOBACTER BAUMANNII / TINCION DE GRAM ===
  b015: null, // === AQUI VA IMAGEN MICROSCOPICA DE NEISSERIA GONORRHOEAE / TINCION DE GRAM ===
  b016: null, // === AQUI VA IMAGEN MICROSCOPICA DE NEISSERIA MENINGITIDIS / TINCION DE GRAM ===
  b017: null, // === AQUI VA IMAGEN MICROSCOPICA DE HAEMOPHILUS INFLUENZAE / TINCION DE GRAM ===
  b018: null, // === AQUI VA IMAGEN MICROSCOPICA DE CORYNEBACTERIUM DIPHTHERIAE / TINCION DE GRAM ===
  b019: null, // === AQUI VA IMAGEN MICROSCOPICA DE BACILLUS CEREUS / TINCION DE GRAM ===
  b020: null, // === AQUI VA IMAGEN MICROSCOPICA DE CLOSTRIDIOIDES DIFFICILE / TINCION DE GRAM ===
  b021: null, // === AQUI VA IMAGEN MICROSCOPICA DE LISTERIA MONOCYTOGENES / TINCION DE GRAM ===
  b022: null, // === AQUI VA IMAGEN MICROSCOPICA DE MYCOBACTERIUM TUBERCULOSIS / TINCION DE GRAM ===
  b023: null, // === AQUI VA IMAGEN MICROSCOPICA DE HELICOBACTER PYLORI / TINCION DE GRAM ===
  b024: null, // === AQUI VA IMAGEN MICROSCOPICA DE CAMPYLOBACTER JEJUNI / TINCION DE GRAM ===
  b025: null, // === AQUI VA IMAGEN MICROSCOPICA DE VIBRIO CHOLERAE / TINCION DE GRAM ===
  b026: null, // === AQUI VA IMAGEN MICROSCOPICA DE TREPONEMA PALLIDUM / TINCION DE GRAM ===
  b027: null, // === AQUI VA IMAGEN MICROSCOPICA DE CHLAMYDIA TRACHOMATIS / TINCION DE GRAM ===
  b028: null, // === AQUI VA IMAGEN MICROSCOPICA DE MYCOPLASMA PNEUMONIAE / TINCION DE GRAM ===
  b029: null, // === AQUI VA IMAGEN MICROSCOPICA DE STAPHYLOCOCCUS LUGDUNENSIS / TINCION DE GRAM ===
  b030: null, // === AQUI VA IMAGEN MICROSCOPICA DE ENTEROCOCCUS FAECIUM / TINCION DE GRAM ===
  b031: null, // === AQUI VA IMAGEN MICROSCOPICA DE BACILLUS ANTHRACIS / TINCION DE GRAM ===
  b032: null, // === AQUI VA IMAGEN MICROSCOPICA DE CLOSTRIDIUM PERFRINGENS / TINCION DE GRAM ===
  b033: null, // === AQUI VA IMAGEN MICROSCOPICA DE CLOSTRIDIUM TETANI / TINCION DE GRAM ===
  b034: null, // === AQUI VA IMAGEN MICROSCOPICA DE CLOSTRIDIUM BOTULINUM / TINCION DE GRAM ===
  b035: null, // === AQUI VA IMAGEN MICROSCOPICA DE ENTEROBACTER CLOACAE / TINCION DE GRAM ===
  b036: null, // === AQUI VA IMAGEN MICROSCOPICA DE SERRATIA MARCESCENS / TINCION DE GRAM ===
  b037: null, // === AQUI VA IMAGEN MICROSCOPICA DE MORGANELLA MORGANII / TINCION DE GRAM ===
  b038: null, // === AQUI VA IMAGEN MICROSCOPICA DE STENOTROPHOMONAS MALTOPHILIA / TINCION DE GRAM ===
  b039: null, // === AQUI VA IMAGEN MICROSCOPICA DE MORAXELLA CATARRHALIS / TINCION DE GRAM ===
  b040: null, // === AQUI VA IMAGEN MICROSCOPICA DE BORDETELLA PERTUSSIS / TINCION DE GRAM ===
  b041: null, // === AQUI VA IMAGEN MICROSCOPICA DE LEGIONELLA PNEUMOPHILA / TINCION DE GRAM ===
  b042: null, // === AQUI VA IMAGEN MICROSCOPICA DE YERSINIA ENTEROCOLITICA / TINCION DE GRAM ===
  b043: null, // === AQUI VA IMAGEN MICROSCOPICA DE BORRELIA BURGDORFERI / TINCION DE GRAM ===
  b044: null, // === AQUI VA IMAGEN MICROSCOPICA DE LEPTOSPIRA INTERROGANS / TINCION DE GRAM ===
  b045: null, // === AQUI VA IMAGEN MICROSCOPICA DE RICKETTSIA RICKETTSII / TINCION DE GRAM ===
  b046: null, // === AQUI VA IMAGEN MICROSCOPICA DE UREAPLASMA UREALYTICUM / TINCION DE GRAM ===
  v001: null, // === AQUI VA IMAGEN MICROSCOPICA DE VIRUS DE LA INFLUENZA / TINCION DE GRAM ===
  v002: null, // === AQUI VA IMAGEN MICROSCOPICA DE SARS-COV-2 / TINCION DE GRAM ===
  v003: null, // === AQUI VA IMAGEN MICROSCOPICA DE VIRUS DEL HERPES SIMPLE (VHS-1 / VHS-2) / TINCION DE GRAM ===
  v004: null, // === AQUI VA IMAGEN MICROSCOPICA DE VIRUS VARICELA-ZÓSTER / TINCION DE GRAM ===
  v005: null, // === AQUI VA IMAGEN MICROSCOPICA DE VIRUS DE EPSTEIN-BARR / TINCION DE GRAM ===
  v006: null, // === AQUI VA IMAGEN MICROSCOPICA DE CITOMEGALOVIRUS / TINCION DE GRAM ===
  v007: null, // === AQUI VA IMAGEN MICROSCOPICA DE VIRUS DE LA HEPATITIS B / TINCION DE GRAM ===
  v008: null, // === AQUI VA IMAGEN MICROSCOPICA DE VIRUS DE LA HEPATITIS C / TINCION DE GRAM ===
  v009: null, // === AQUI VA IMAGEN MICROSCOPICA DE VIRUS DE LA INMUNODEFICIENCIA HUMANA (VIH) / TINCION DE GRAM ===
  v010: null, // === AQUI VA IMAGEN MICROSCOPICA DE ROTAVIRUS / TINCION DE GRAM ===
  v011: null, // === AQUI VA IMAGEN MICROSCOPICA DE NOROVIRUS / TINCION DE GRAM ===
  v012: null, // === AQUI VA IMAGEN MICROSCOPICA DE VIRUS DEL PAPILOMA HUMANO (VPH) / TINCION DE GRAM ===
  v013: null, // === AQUI VA IMAGEN MICROSCOPICA DE ADENOVIRUS / TINCION DE GRAM ===
  v014: null, // === AQUI VA IMAGEN MICROSCOPICA DE VIRUS DEL DENGUE / TINCION DE GRAM ===
  v015: null, // === AQUI VA IMAGEN MICROSCOPICA DE VIRUS RESPIRATORIO SINCITIAL (VRS) / TINCION DE GRAM ===
  v016: null, // === AQUI VA IMAGEN MICROSCOPICA DE VIRUS DE PARAINFLUENZA HUMANA / TINCION DE GRAM ===
  v017: null, // === AQUI VA IMAGEN MICROSCOPICA DE RINOVIRUS HUMANO / TINCION DE GRAM ===
  v018: null, // === AQUI VA IMAGEN MICROSCOPICA DE VIRUS DE LA HEPATITIS A / TINCION DE GRAM ===
  v019: null, // === AQUI VA IMAGEN MICROSCOPICA DE VIRUS DE LA HEPATITIS E / TINCION DE GRAM ===
  v020: null, // === AQUI VA IMAGEN MICROSCOPICA DE VIRUS DE LA RABIA / TINCION DE GRAM ===
  v021: null, // === AQUI VA IMAGEN MICROSCOPICA DE PARVOVIRUS B19 / TINCION DE GRAM ===
  v022: null, // === AQUI VA IMAGEN MICROSCOPICA DE VIRUS DEL ZIKA / TINCION DE GRAM ===
  v023: null, // === AQUI VA IMAGEN MICROSCOPICA DE VIRUS DEL CHIKUNGUNYA / TINCION DE GRAM ===
  v024: null, // === AQUI VA IMAGEN MICROSCOPICA DE VIRUS DE LA FIEBRE AMARILLA / TINCION DE GRAM ===
  h001: null, // === AQUI VA IMAGEN MICROSCOPICA DE CANDIDA ALBICANS / TINCION DE GRAM ===
  h002: null, // === AQUI VA IMAGEN MICROSCOPICA DE CRYPTOCOCCUS NEOFORMANS / TINCION DE GRAM ===
  h003: null, // === AQUI VA IMAGEN MICROSCOPICA DE ASPERGILLUS FUMIGATUS / TINCION DE GRAM ===
  h004: null, // === AQUI VA IMAGEN MICROSCOPICA DE TRICHOPHYTON RUBRUM / TINCION DE GRAM ===
  h005: null, // === AQUI VA IMAGEN MICROSCOPICA DE MICROSPORUM CANIS / TINCION DE GRAM ===
  h006: null, // === AQUI VA IMAGEN MICROSCOPICA DE HISTOPLASMA CAPSULATUM / TINCION DE GRAM ===
  h007: null, // === AQUI VA IMAGEN MICROSCOPICA DE MALASSEZIA FURFUR / TINCION DE GRAM ===
  h008: null, // === AQUI VA IMAGEN MICROSCOPICA DE SPOROTHRIX SCHENCKII / TINCION DE GRAM ===
  h009: null, // === AQUI VA IMAGEN MICROSCOPICA DE CANDIDA GLABRATA / TINCION DE GRAM ===
  h010: null, // === AQUI VA IMAGEN MICROSCOPICA DE CANDIDA KRUSEI / TINCION DE GRAM ===
  h011: null, // === AQUI VA IMAGEN MICROSCOPICA DE CANDIDA AURIS / TINCION DE GRAM ===
  h012: null, // === AQUI VA IMAGEN MICROSCOPICA DE CRYPTOCOCCUS GATTII / TINCION DE GRAM ===
  h013: null, // === AQUI VA IMAGEN MICROSCOPICA DE COCCIDIOIDES IMMITIS / TINCION DE GRAM ===
  h014: null, // === AQUI VA IMAGEN MICROSCOPICA DE PARACOCCIDIOIDES BRASILIENSIS / TINCION DE GRAM ===
  h015: null, // === AQUI VA IMAGEN MICROSCOPICA DE ASPERGILLUS FLAVUS / TINCION DE GRAM ===
  h016: null, // === AQUI VA IMAGEN MICROSCOPICA DE RHIZOPUS SPP. / TINCION DE GRAM ===
  h017: null, // === AQUI VA IMAGEN MICROSCOPICA DE PNEUMOCYSTIS JIROVECII / TINCION DE GRAM ===
  h018: null, // === AQUI VA IMAGEN MICROSCOPICA DE TRICHOPHYTON MENTAGROPHYTES / TINCION DE GRAM ===
  p001: null, // === AQUI VA IMAGEN MICROSCOPICA DE ENTAMOEBA HISTOLYTICA / TINCION DE GRAM ===
  p002: null, // === AQUI VA IMAGEN MICROSCOPICA DE GIARDIA DUODENALIS (LAMBLIA) / TINCION DE GRAM ===
  p003: null, // === AQUI VA IMAGEN MICROSCOPICA DE TRICHOMONAS VAGINALIS / TINCION DE GRAM ===
  p004: null, // === AQUI VA IMAGEN MICROSCOPICA DE PLASMODIUM FALCIPARUM / TINCION DE GRAM ===
  p005: null, // === AQUI VA IMAGEN MICROSCOPICA DE TOXOPLASMA GONDII / TINCION DE GRAM ===
  p006: null, // === AQUI VA IMAGEN MICROSCOPICA DE ASCARIS LUMBRICOIDES / TINCION DE GRAM ===
  p007: null, // === AQUI VA IMAGEN MICROSCOPICA DE ENTEROBIUS VERMICULARIS / TINCION DE GRAM ===
  p008: null, // === AQUI VA IMAGEN MICROSCOPICA DE TAENIA SOLIUM / TINCION DE GRAM ===
  p009: null, // === AQUI VA IMAGEN MICROSCOPICA DE PLASMODIUM VIVAX / TINCION DE GRAM ===
  p010: null, // === AQUI VA IMAGEN MICROSCOPICA DE STRONGYLOIDES STERCORALIS / TINCION DE GRAM ===
  p011: null, // === AQUI VA IMAGEN MICROSCOPICA DE ANCYLOSTOMA DUODENALE / TINCION DE GRAM ===
  p012: null, // === AQUI VA IMAGEN MICROSCOPICA DE NECATOR AMERICANUS / TINCION DE GRAM ===
  p013: null, // === AQUI VA IMAGEN MICROSCOPICA DE TRICHURIS TRICHIURA / TINCION DE GRAM ===
  p014: null, // === AQUI VA IMAGEN MICROSCOPICA DE TAENIA SAGINATA / TINCION DE GRAM ===
  p015: null, // === AQUI VA IMAGEN MICROSCOPICA DE SCHISTOSOMA MANSONI / TINCION DE GRAM ===
  p016: null, // === AQUI VA IMAGEN MICROSCOPICA DE ECHINOCOCCUS GRANULOSUS / TINCION DE GRAM ===
  p017: null, // === AQUI VA IMAGEN MICROSCOPICA DE CRYPTOSPORIDIUM SPP. / TINCION DE GRAM ===
  p018: null, // === AQUI VA IMAGEN MICROSCOPICA DE BALANTIDIUM COLI / TINCION DE GRAM ===
};

// MICROORGANISMOS (BACTERIAS, VIRUS, HONGOS, PARASITOS) — AGAR (fotografia del microorganismo en placa/cultivo)
export const imagenesAgar: MapaImagenes = {
  b001: null, // === AQUI VA IMAGEN DE STAPHYLOCOCCUS AUREUS EN AGAR / CULTIVO ===
  b002: null, // === AQUI VA IMAGEN DE STAPHYLOCOCCUS EPIDERMIDIS EN AGAR / CULTIVO ===
  b003: null, // === AQUI VA IMAGEN DE STAPHYLOCOCCUS SAPROPHYTICUS EN AGAR / CULTIVO ===
  b004: null, // === AQUI VA IMAGEN DE STREPTOCOCCUS PYOGENES EN AGAR / CULTIVO ===
  b005: null, // === AQUI VA IMAGEN DE STREPTOCOCCUS AGALACTIAE EN AGAR / CULTIVO ===
  b006: null, // === AQUI VA IMAGEN DE STREPTOCOCCUS PNEUMONIAE EN AGAR / CULTIVO ===
  b007: null, // === AQUI VA IMAGEN DE ENTEROCOCCUS FAECALIS EN AGAR / CULTIVO ===
  b008: null, // === AQUI VA IMAGEN DE ESCHERICHIA COLI EN AGAR / CULTIVO ===
  b009: null, // === AQUI VA IMAGEN DE KLEBSIELLA PNEUMONIAE EN AGAR / CULTIVO ===
  b010: null, // === AQUI VA IMAGEN DE PROTEUS MIRABILIS EN AGAR / CULTIVO ===
  b011: null, // === AQUI VA IMAGEN DE SALMONELLA ENTERICA EN AGAR / CULTIVO ===
  b012: null, // === AQUI VA IMAGEN DE SHIGELLA FLEXNERI EN AGAR / CULTIVO ===
  b013: null, // === AQUI VA IMAGEN DE PSEUDOMONAS AERUGINOSA EN AGAR / CULTIVO ===
  b014: null, // === AQUI VA IMAGEN DE ACINETOBACTER BAUMANNII EN AGAR / CULTIVO ===
  b015: null, // === AQUI VA IMAGEN DE NEISSERIA GONORRHOEAE EN AGAR / CULTIVO ===
  b016: null, // === AQUI VA IMAGEN DE NEISSERIA MENINGITIDIS EN AGAR / CULTIVO ===
  b017: null, // === AQUI VA IMAGEN DE HAEMOPHILUS INFLUENZAE EN AGAR / CULTIVO ===
  b018: null, // === AQUI VA IMAGEN DE CORYNEBACTERIUM DIPHTHERIAE EN AGAR / CULTIVO ===
  b019: null, // === AQUI VA IMAGEN DE BACILLUS CEREUS EN AGAR / CULTIVO ===
  b020: null, // === AQUI VA IMAGEN DE CLOSTRIDIOIDES DIFFICILE EN AGAR / CULTIVO ===
  b021: null, // === AQUI VA IMAGEN DE LISTERIA MONOCYTOGENES EN AGAR / CULTIVO ===
  b022: null, // === AQUI VA IMAGEN DE MYCOBACTERIUM TUBERCULOSIS EN AGAR / CULTIVO ===
  b023: null, // === AQUI VA IMAGEN DE HELICOBACTER PYLORI EN AGAR / CULTIVO ===
  b024: null, // === AQUI VA IMAGEN DE CAMPYLOBACTER JEJUNI EN AGAR / CULTIVO ===
  b025: null, // === AQUI VA IMAGEN DE VIBRIO CHOLERAE EN AGAR / CULTIVO ===
  b026: null, // === AQUI VA IMAGEN DE TREPONEMA PALLIDUM EN AGAR / CULTIVO ===
  b027: null, // === AQUI VA IMAGEN DE CHLAMYDIA TRACHOMATIS EN AGAR / CULTIVO ===
  b028: null, // === AQUI VA IMAGEN DE MYCOPLASMA PNEUMONIAE EN AGAR / CULTIVO ===
  b029: null, // === AQUI VA IMAGEN DE STAPHYLOCOCCUS LUGDUNENSIS EN AGAR / CULTIVO ===
  b030: null, // === AQUI VA IMAGEN DE ENTEROCOCCUS FAECIUM EN AGAR / CULTIVO ===
  b031: null, // === AQUI VA IMAGEN DE BACILLUS ANTHRACIS EN AGAR / CULTIVO ===
  b032: null, // === AQUI VA IMAGEN DE CLOSTRIDIUM PERFRINGENS EN AGAR / CULTIVO ===
  b033: null, // === AQUI VA IMAGEN DE CLOSTRIDIUM TETANI EN AGAR / CULTIVO ===
  b034: null, // === AQUI VA IMAGEN DE CLOSTRIDIUM BOTULINUM EN AGAR / CULTIVO ===
  b035: null, // === AQUI VA IMAGEN DE ENTEROBACTER CLOACAE EN AGAR / CULTIVO ===
  b036: null, // === AQUI VA IMAGEN DE SERRATIA MARCESCENS EN AGAR / CULTIVO ===
  b037: null, // === AQUI VA IMAGEN DE MORGANELLA MORGANII EN AGAR / CULTIVO ===
  b038: null, // === AQUI VA IMAGEN DE STENOTROPHOMONAS MALTOPHILIA EN AGAR / CULTIVO ===
  b039: null, // === AQUI VA IMAGEN DE MORAXELLA CATARRHALIS EN AGAR / CULTIVO ===
  b040: null, // === AQUI VA IMAGEN DE BORDETELLA PERTUSSIS EN AGAR / CULTIVO ===
  b041: null, // === AQUI VA IMAGEN DE LEGIONELLA PNEUMOPHILA EN AGAR / CULTIVO ===
  b042: null, // === AQUI VA IMAGEN DE YERSINIA ENTEROCOLITICA EN AGAR / CULTIVO ===
  b043: null, // === AQUI VA IMAGEN DE BORRELIA BURGDORFERI EN AGAR / CULTIVO ===
  b044: null, // === AQUI VA IMAGEN DE LEPTOSPIRA INTERROGANS EN AGAR / CULTIVO ===
  b045: null, // === AQUI VA IMAGEN DE RICKETTSIA RICKETTSII EN AGAR / CULTIVO ===
  b046: null, // === AQUI VA IMAGEN DE UREAPLASMA UREALYTICUM EN AGAR / CULTIVO ===
  v001: null, // === AQUI VA IMAGEN DE VIRUS DE LA INFLUENZA EN AGAR / CULTIVO ===
  v002: null, // === AQUI VA IMAGEN DE SARS-COV-2 EN AGAR / CULTIVO ===
  v003: null, // === AQUI VA IMAGEN DE VIRUS DEL HERPES SIMPLE (VHS-1 / VHS-2) EN AGAR / CULTIVO ===
  v004: null, // === AQUI VA IMAGEN DE VIRUS VARICELA-ZÓSTER EN AGAR / CULTIVO ===
  v005: null, // === AQUI VA IMAGEN DE VIRUS DE EPSTEIN-BARR EN AGAR / CULTIVO ===
  v006: null, // === AQUI VA IMAGEN DE CITOMEGALOVIRUS EN AGAR / CULTIVO ===
  v007: null, // === AQUI VA IMAGEN DE VIRUS DE LA HEPATITIS B EN AGAR / CULTIVO ===
  v008: null, // === AQUI VA IMAGEN DE VIRUS DE LA HEPATITIS C EN AGAR / CULTIVO ===
  v009: null, // === AQUI VA IMAGEN DE VIRUS DE LA INMUNODEFICIENCIA HUMANA (VIH) EN AGAR / CULTIVO ===
  v010: null, // === AQUI VA IMAGEN DE ROTAVIRUS EN AGAR / CULTIVO ===
  v011: null, // === AQUI VA IMAGEN DE NOROVIRUS EN AGAR / CULTIVO ===
  v012: null, // === AQUI VA IMAGEN DE VIRUS DEL PAPILOMA HUMANO (VPH) EN AGAR / CULTIVO ===
  v013: null, // === AQUI VA IMAGEN DE ADENOVIRUS EN AGAR / CULTIVO ===
  v014: null, // === AQUI VA IMAGEN DE VIRUS DEL DENGUE EN AGAR / CULTIVO ===
  v015: null, // === AQUI VA IMAGEN DE VIRUS RESPIRATORIO SINCITIAL (VRS) EN AGAR / CULTIVO ===
  v016: null, // === AQUI VA IMAGEN DE VIRUS DE PARAINFLUENZA HUMANA EN AGAR / CULTIVO ===
  v017: null, // === AQUI VA IMAGEN DE RINOVIRUS HUMANO EN AGAR / CULTIVO ===
  v018: null, // === AQUI VA IMAGEN DE VIRUS DE LA HEPATITIS A EN AGAR / CULTIVO ===
  v019: null, // === AQUI VA IMAGEN DE VIRUS DE LA HEPATITIS E EN AGAR / CULTIVO ===
  v020: null, // === AQUI VA IMAGEN DE VIRUS DE LA RABIA EN AGAR / CULTIVO ===
  v021: null, // === AQUI VA IMAGEN DE PARVOVIRUS B19 EN AGAR / CULTIVO ===
  v022: null, // === AQUI VA IMAGEN DE VIRUS DEL ZIKA EN AGAR / CULTIVO ===
  v023: null, // === AQUI VA IMAGEN DE VIRUS DEL CHIKUNGUNYA EN AGAR / CULTIVO ===
  v024: null, // === AQUI VA IMAGEN DE VIRUS DE LA FIEBRE AMARILLA EN AGAR / CULTIVO ===
  h001: null, // === AQUI VA IMAGEN DE CANDIDA ALBICANS EN AGAR / CULTIVO ===
  h002: null, // === AQUI VA IMAGEN DE CRYPTOCOCCUS NEOFORMANS EN AGAR / CULTIVO ===
  h003: null, // === AQUI VA IMAGEN DE ASPERGILLUS FUMIGATUS EN AGAR / CULTIVO ===
  h004: null, // === AQUI VA IMAGEN DE TRICHOPHYTON RUBRUM EN AGAR / CULTIVO ===
  h005: null, // === AQUI VA IMAGEN DE MICROSPORUM CANIS EN AGAR / CULTIVO ===
  h006: null, // === AQUI VA IMAGEN DE HISTOPLASMA CAPSULATUM EN AGAR / CULTIVO ===
  h007: null, // === AQUI VA IMAGEN DE MALASSEZIA FURFUR EN AGAR / CULTIVO ===
  h008: null, // === AQUI VA IMAGEN DE SPOROTHRIX SCHENCKII EN AGAR / CULTIVO ===
  h009: null, // === AQUI VA IMAGEN DE CANDIDA GLABRATA EN AGAR / CULTIVO ===
  h010: null, // === AQUI VA IMAGEN DE CANDIDA KRUSEI EN AGAR / CULTIVO ===
  h011: null, // === AQUI VA IMAGEN DE CANDIDA AURIS EN AGAR / CULTIVO ===
  h012: null, // === AQUI VA IMAGEN DE CRYPTOCOCCUS GATTII EN AGAR / CULTIVO ===
  h013: null, // === AQUI VA IMAGEN DE COCCIDIOIDES IMMITIS EN AGAR / CULTIVO ===
  h014: null, // === AQUI VA IMAGEN DE PARACOCCIDIOIDES BRASILIENSIS EN AGAR / CULTIVO ===
  h015: null, // === AQUI VA IMAGEN DE ASPERGILLUS FLAVUS EN AGAR / CULTIVO ===
  h016: null, // === AQUI VA IMAGEN DE RHIZOPUS SPP. EN AGAR / CULTIVO ===
  h017: null, // === AQUI VA IMAGEN DE PNEUMOCYSTIS JIROVECII EN AGAR / CULTIVO ===
  h018: null, // === AQUI VA IMAGEN DE TRICHOPHYTON MENTAGROPHYTES EN AGAR / CULTIVO ===
  p001: null, // === AQUI VA IMAGEN DE ENTAMOEBA HISTOLYTICA EN AGAR / CULTIVO ===
  p002: null, // === AQUI VA IMAGEN DE GIARDIA DUODENALIS (LAMBLIA) EN AGAR / CULTIVO ===
  p003: null, // === AQUI VA IMAGEN DE TRICHOMONAS VAGINALIS EN AGAR / CULTIVO ===
  p004: null, // === AQUI VA IMAGEN DE PLASMODIUM FALCIPARUM EN AGAR / CULTIVO ===
  p005: null, // === AQUI VA IMAGEN DE TOXOPLASMA GONDII EN AGAR / CULTIVO ===
  p006: null, // === AQUI VA IMAGEN DE ASCARIS LUMBRICOIDES EN AGAR / CULTIVO ===
  p007: null, // === AQUI VA IMAGEN DE ENTEROBIUS VERMICULARIS EN AGAR / CULTIVO ===
  p008: null, // === AQUI VA IMAGEN DE TAENIA SOLIUM EN AGAR / CULTIVO ===
  p009: null, // === AQUI VA IMAGEN DE PLASMODIUM VIVAX EN AGAR / CULTIVO ===
  p010: null, // === AQUI VA IMAGEN DE STRONGYLOIDES STERCORALIS EN AGAR / CULTIVO ===
  p011: null, // === AQUI VA IMAGEN DE ANCYLOSTOMA DUODENALE EN AGAR / CULTIVO ===
  p012: null, // === AQUI VA IMAGEN DE NECATOR AMERICANUS EN AGAR / CULTIVO ===
  p013: null, // === AQUI VA IMAGEN DE TRICHURIS TRICHIURA EN AGAR / CULTIVO ===
  p014: null, // === AQUI VA IMAGEN DE TAENIA SAGINATA EN AGAR / CULTIVO ===
  p015: null, // === AQUI VA IMAGEN DE SCHISTOSOMA MANSONI EN AGAR / CULTIVO ===
  p016: null, // === AQUI VA IMAGEN DE ECHINOCOCCUS GRANULOSUS EN AGAR / CULTIVO ===
  p017: null, // === AQUI VA IMAGEN DE CRYPTOSPORIDIUM SPP. EN AGAR / CULTIVO ===
  p018: null, // === AQUI VA IMAGEN DE BALANTIDIUM COLI EN AGAR / CULTIVO ===
};

// PRUEBAS DE LABORATORIO / BIOQUIMICAS (seccion aparte, no forma parte de la galeria del microorganismo)
export const imagenesPruebas: MapaImagenes = {
  catalasa: null, // === PONER AQUI IMAGEN DE CATALASA ===
  coagulasa: null, // === PONER AQUI IMAGEN DE COAGULASA ===
  oxidasa: null, // === PONER AQUI IMAGEN DE OXIDASA ===
  dnasa: null, // === PONER AQUI IMAGEN DE DNASA ===
  ureasa: null, // === PONER AQUI IMAGEN DE UREASA ===
  indol: null, // === PONER AQUI IMAGEN DE INDOL ===
  citrato: null, // === PONER AQUI IMAGEN DE CITRATO (SIMMONS) ===
  tsi: null, // === PONER AQUI IMAGEN DE TSI (TRIPLE AZÚCAR HIERRO) ===
  pyr: null, // === PONER AQUI IMAGEN DE PYR ===
  "bilis-esculina": null, // === PONER AQUI IMAGEN DE BILIS ESCULINA ===
  novobiocina: null, // === PONER AQUI IMAGEN DE NOVOBIOCINA ===
  optoquina: null, // === PONER AQUI IMAGEN DE OPTOQUINA ===
  bacitracina: null, // === PONER AQUI IMAGEN DE BACITRACINA ===
  hemolisis: null, // === PONER AQUI IMAGEN DE HEMÓLISIS EN AGAR SANGRE ===
  "ziehl-neelsen": null, // === PONER AQUI IMAGEN DE ZIEHL-NEELSEN ===
  gram: null, // === PONER AQUI IMAGEN DE TINCIÓN DE GRAM ===
  koh: null, // === PONER AQUI IMAGEN DE KOH (HIDRÓXIDO DE POTASIO) ===
  "tinta-china": null, // === PONER AQUI IMAGEN DE TINTA CHINA ===
  sim: null, // === PONER AQUI IMAGEN DE SIM (SULFURO-INDOL-MOTILIDAD) ===
  mio: null, // === PONER AQUI IMAGEN DE MIO (MOTILIDAD-INDOL-ORNITINA) ===
  lia: null, // === PONER AQUI IMAGEN DE LIA (LISINA HIERRO AGAR) ===
  mr: null, // === PONER AQUI IMAGEN DE ROJO DE METILO (MR) ===
  vp: null, // === PONER AQUI IMAGEN DE VOGES-PROSKAUER (VP) ===
  malonato: null, // === PONER AQUI IMAGEN DE MALONATO ===
  onpg: null, // === PONER AQUI IMAGEN DE ONPG (ORTO-NITROFENIL-Β-D-GALACTOPIRANÓSIDO) ===
  fenilalanina: null, // === PONER AQUI IMAGEN DE FENILALANINA DESAMINASA (PDA) ===
  lisina: null, // === PONER AQUI IMAGEN DE LISINA DESCARBOXILASA (LDC) ===
  ornitina: null, // === PONER AQUI IMAGEN DE ORNITINA DESCARBOXILASA (ODC) ===
  arginina: null, // === PONER AQUI IMAGEN DE ARGININA DIHIDROLASA (ADH) ===
  gelatinasa: null, // === PONER AQUI IMAGEN DE GELATINASA ===
  nitratos: null, // === PONER AQUI IMAGEN DE REDUCCIÓN DE NITRATOS ===
  camp: null, // === PONER AQUI IMAGEN DE CAMP ===
  "solubilidad-bilis": null, // === PONER AQUI IMAGEN DE SOLUBILIDAD EN BILIS ===
};

// MEDIOS DE CULTIVO — imagenes GENERICAS del aspecto del medio (sin microorganismo)
// Esta seccion es independiente de la galeria de cada microorganismo. NO mezclar.
export const imagenesMedios: MapaImagenes = {
  "agar-sangre": null, // === AQUI VA IMAGEN GENERICA DE AGAR SANGRE ===
  "agar-chocolate": null, // === AQUI VA IMAGEN GENERICA DE AGAR CHOCOLATE ===
  macconkey: null, // === AQUI VA IMAGEN GENERICA DE AGAR MACCONKEY ===
  cled: null, // === AQUI VA IMAGEN GENERICA DE AGAR CLED ===
  emb: null, // === AQUI VA IMAGEN GENERICA DE AGAR EMB (EOSINA-AZUL DE METILENO) ===
  "manitol-salado": null, // === AQUI VA IMAGEN GENERICA DE AGAR MANITOL SALADO ===
  cetrimida: null, // === AQUI VA IMAGEN GENERICA DE AGAR CETRIMIDA ===
  "thayer-martin": null, // === AQUI VA IMAGEN GENERICA DE AGAR THAYER-MARTIN ===
  xld: null, // === AQUI VA IMAGEN GENERICA DE AGAR XLD ===
  hektoen: null, // === AQUI VA IMAGEN GENERICA DE AGAR HEKTOEN ===
  ss: null, // === AQUI VA IMAGEN GENERICA DE AGAR SS (SALMONELLA-SHIGELLA) ===
  tcbs: null, // === AQUI VA IMAGEN GENERICA DE AGAR TCBS ===
  "lowenstein-jensen": null, // === AQUI VA IMAGEN GENERICA DE AGAR LOWENSTEIN-JENSEN ===
  sabouraud: null, // === AQUI VA IMAGEN GENERICA DE AGAR SABOURAUD ===
  "mueller-hinton": null, // === AQUI VA IMAGEN GENERICA DE AGAR MUELLER-HINTON ===
  "campy-bap": null, // === AQUI VA IMAGEN GENERICA DE AGAR CAMPY-BAP ===
  middlebrook: null, // === AQUI VA IMAGEN GENERICA DE MEDIO DE MIDDLEBROOK (7H10/7H11) ===
  "agar-cna": null, // === AQUI VA IMAGEN GENERICA DE AGAR CNA (COLISTINA-ÁCIDO NALIDÍXICO) ===
  "agar-candida": null, // === AQUI VA IMAGEN GENERICA DE AGAR CROMOGÉNICO PARA CANDIDA (CHROMAGAR CANDIDA) ===
};

// PROCEDIMIENTOS (seccion aparte, no forma parte de este pedido)
export const imagenesProcedimientos: MapaImagenes = {
  proc001: null, // === PONER AQUI IMAGEN DE HEMOCULTIVO ===
  proc002: null, // === PONER AQUI IMAGEN DE UROCULTIVO ===
  proc003: null, // === PONER AQUI IMAGEN DE COPROCULTIVO ===
  proc004: null, // === PONER AQUI IMAGEN DE CULTIVO DE SECRECIÓN FARÍNGEA ===
  proc005: null, // === PONER AQUI IMAGEN DE TINCIÓN DE GRAM ===
  proc006: null, // === PONER AQUI IMAGEN DE ZIEHL-NEELSEN (BACILOSCOPIA) ===
  proc007: null, // === PONER AQUI IMAGEN DE ANTIBIOGRAMA POR DIFUSIÓN EN DISCO (KIRBY-BAUER) ===
  proc008: null, // === PONER AQUI IMAGEN DE EXAMEN DIRECTO CON KOH ===
  proc009: null, // === PONER AQUI IMAGEN DE CULTIVO MICOLÓGICO EN AGAR SABOURAUD ===
  proc010: null, // === PONER AQUI IMAGEN DE PRUEBA DEL TUBO GERMINATIVO ===
  proc011: null, // === PONER AQUI IMAGEN DE EXAMEN DIRECTO CON SOLUCIÓN SALINA Y LUGOL ===
  proc012: null, // === PONER AQUI IMAGEN DE TÉCNICA DE GRAHAM (CINTA ADHESIVA PERIANAL) ===
  proc013: null, // === PONER AQUI IMAGEN DE MÉTODO DE CONCENTRACIÓN POR SEDIMENTACIÓN (TIPO RITCHIE/FAUST) ===
  proc014: null, // === PONER AQUI IMAGEN DE GOTA GRUESA Y GOTA FINA (HEMOPARÁSITOS) ===
  proc015: null, // === PONER AQUI IMAGEN DE TOMA Y TRANSPORTE DE MUESTRAS MICROBIOLÓGICAS ===
  proc016: null, // === PONER AQUI IMAGEN DE PRINCIPIOS DE BIOSEGURIDAD EN EL LABORATORIO DE MICROBIOLOGÍA ===
};

// Devuelve la imagen manual de un organismo, prueba, medio o procedimiento si existe.
export function getImagen(mapa: MapaImagenes, id: string): string | null {
  return mapa[id] ?? null;
}
